bin/hiera

The Hiera CLI uses ruby's optparse module to pull options out of ARGV. So
does Mcollective. The problem is that the CLI parses some options, comes
across a need for mcollective, then calls it immediately before the rest of
ARGV is parsed. That creates some weird results.  Specifically, it adds an
ordering requirement between -c and -m on the command line that is non-obvious
and undocumented.  This patch moves scope loading into a later code chunk,
after optparse is done with what it's doing.

(HI-306) Break options parsing away from Mcollective scope load

---

acceptance_tests/tests/yaml_backend/00-setup.rb
acceptance_tests/tests/yaml_backend/01-lookup_data_without_a_key.rb
acceptance_tests/tests/yaml_backend/02-lookup_data_with_no_options.rb
acceptance_tests/tests/yaml_backend/03-lookup_data_with_a_scope.rb
acceptance_tests/tests/yaml_backend/04-lookup_data_with_array_search.rb
acceptance_tests/tests/yaml_backend/05-lookup_data_with_hash_search.rb

This commit changes the node role that the acceptance tests run on from
`master` to `agent`.
This change is required in order for the tests to run test configurations
using the All In One agent packaging. The AIO testing applies directly to
agent nodes, and since Hiera functionality does not require a master, pinning
the test execution to the master role should be generalized to the agent.

(HI-327) Set acceptance tests to run on agent role

---

acceptance_tests/tests/yaml_backend/00-setup.rb

We parameterized most of the hard coded paths, unfortunately we don't
have a parameterization for the config hiera uses when it is ran as a
CLI tool (because it uses a different one than when it's ran as a
library, natch). This reverts the functionality of the setup step to
create the hiera.yaml file needed by the rest of the tests in the
/etc/hiera.yaml location that the CLI version of hiera expects.

(maint) Don't Parameterize the hiera CLI config

---

ext/hiera.yaml
lib/hiera/util.rb
spec/unit/util_spec.rb

Changes the config_dir to '/etc/puppetlabs/agent/code' and the
var_dir to '/etc/puppetlabs/agent/code/hieradata' for posix style
systems. The corresponding paths for windows are unchanged.
The changes have been tested by running the spec tests in
current puppet/master branch while using this hiera source.

(HI-298) Change config-dir and var-dir settings

---

README.md
lib/hiera/backend.rb
lib/hiera/interpolate.rb
spec/unit/backend_spec.rb

Previously hiera would not recognize qualified names containing
dots. This commit changes the lookup so that a key containing
dots can be used for doing qualified lookups in values that are
known to be hashes. For example:
$ hiera user
{"name"=>"kim", "home"=>"/home/kim"}
$ hiera user.name
kim
$ hiera ssh_users
["root", "jeff", "gary", "hunter"]
$ hiera ssh_users.0
root

(HI-14) Implement structure traversal lookup

---

lib/hiera/backend.rb

The qualified lookup assumed that the target for the lookup was
either an Array or a Hash. That assumtpion was incorrect. It can
be either an Array or something that responds to ```[]``` (such as a
Hiera::Scope).

(HI-14) Fix regression caused by incorrect assumption about Hash

---

lib/hiera/backend.rb
lib/hiera/backend/json_backend.rb
lib/hiera/backend/yaml_backend.rb
lib/hiera/interpolate.rb
spec/spec_helper.rb
spec/unit/backend/json_backend_spec.rb
spec/unit/backend/yaml_backend_spec.rb
spec/unit/backend_spec.rb
spec/unit/fixtures/interpolate/config/hiera.yaml
spec/unit/fixtures/interpolate/data/recursive.yaml
spec/unit/interpolate_spec.rb

This commit ensures that only one RecursiveGuard instance is
used in a lookup even if that lookup results in multiple
interpolations.
A backend implementation must add and pass on a fifth
'recurse_guard' argument but the implementation will accept
the old API with four arguments as well for backward
compatibility.

(HI-328) Prevent interpolation recursion

---

acceptance/tests/yaml_backend/00-setup.rb

This commit updates the path to the hiera.yaml file in accordance with the
pathing changes in commit 602c682. This path cannot yet be parameterized and
is hard coded to `/etc/puppetlabs/agent/code/hiera.yaml` in the 00-setup.rb
test.

(HI-298) Update hiera.yaml path in acceptance tests

---

lib/hiera/backend.rb
lib/hiera/backend/json_backend.rb
lib/hiera/backend/yaml_backend.rb
lib/hiera/interpolate.rb
spec/unit/backend/json_backend_spec.rb
spec/unit/backend_spec.rb

The existing implementation of hiera interpolation did not utilize the
order override parameter of lookup. If an interpolated variable was
expected to be looked up in the overridden datasource it would instead
only be looked up in the configured datasources.
This patch passes the order_override parameter down the call stack to
the hiera_interpolate method of the Hiera::Interpolate class. This
method then in turn passes the order_override parameter back into the
Hiera::Backend lookup method. Thereby allowing the overridden datasource
to be searched for lookup values.

(HI-304) Make order override work with interpolation

---

acceptance/tests/yaml_backend/00-setup.rb
ext/hiera.yaml
lib/hiera/util.rb
spec/unit/util_spec.rb

This commit removes the 'agent' segment from the config_dir and
var_dir properties of the Util class. It also updates the sample
and tests (unit and acceptance) to reflect the change.

(HI-298) Strip 'agent/' part of default paths.

---

README.md

Updates README.md based on AIO codedir `/etc/puppetlabs/code` and vardir `/opt/puppetlabs/puppet/cache`

(HI-298) Update README to match AIO paths

---

lib/hiera/backend.rb
lib/hiera/backend/json_backend.rb
lib/hiera/backend/yaml_backend.rb
lib/hiera/interpolate.rb
spec/unit/backend/json_backend_spec.rb
spec/unit/backend/yaml_backend_spec.rb
spec/unit/backend_spec.rb
spec/unit/fixtures/interpolate/config/hiera.yaml
spec/unit/fixtures/interpolate/data/niltest.yaml
spec/unit/interpolate_spec.rb

This commit changes the JSON and YAML backends so that they throws
a :no_such_key exception when the key is missing and returns nil for
a key that is found but has a nil value. The Backend that calls those
backends will recognize this distinction and only use the 'extras'
hash and 'default' value when the key is missing. In contrast, a nil
return will be treated as a valid value and returned to the caller.
In addition to the hiera spec tests, this test has also been spec tested from puppet master.

(HI-337) Distinguish between nil values and missing keys

---

lib/hiera/backend.rb
lib/hiera/config.rb

Make requesting the deep or deeper behavior for the :deep_merge setting
an error if the deep_merge gem is absent.

(HI-274) Requesting deep_merge errors if absent

---

lib/hiera/config.rb
spec/unit/config_spec.rb

Previous commit tried to use Hiera#error, which doesn't exist. Pattern
for errors is to raise an exception, so changed to raising an exception
if deep_merge is requested but unavailable. Added spec tests.

(HI-274) Fix using non-existent Hiera#error

---

acceptance_tests/Rakefile

With Puppet 4.0, we're introducing a break between master and stable
across projects. For a while, Hiera stable should run agaist
Puppet/Facter stable.
Change the acceptance Rake task to make Puppet and Facter branches
configurable.

(maint) Make Puppet/Facter branches configurable for acceptance

---

acceptance/setup/common/00_EnvSetup.rb
acceptance/setup/git/pre-suite/00_EnvSetup.rb

The ci:git:test Rake task used by Jenkins looks for pre-suite
specifically in setup/git. For now we continue to maintain two setup
scripts until the Rake task is cleaned up.

(maint) Restore and update jenkins env

---

acceptance/tests/yaml_backend/00-setup.rb
acceptance/tests/yaml_backend/02-lookup_data_with_no_options.rb
acceptance/tests/yaml_backend/03-lookup_data_with_a_scope.rb
acceptance/tests/yaml_backend/04-lookup_data_with_array_search.rb
acceptance/tests/yaml_backend/05-lookup_data_with_hash_search.rb

Hieradata dir changed in hiera and hasn't been updated in beaker, so
tests fail because creating hieradata dir fails. To avoid this situation
in the future, we query Puppet for the location of codedir and derive
hieradata dir from it.

(HI-340) Fix hieradata path in acceptance tests

---

ext/hiera.yaml
lib/hiera/util.rb
spec/unit/util_spec.rb

Previously, hiera on Windows defaulted to
C:\ProgramData\PuppetLabs\hiera\etc.
This commit updates hiera to use C:\ProgramData\PuppetLabs\code.

(HI-298) Move hiera data to C:\ProgramData\PuppetLabs\code

---

acceptance/Gemfile

Allow beaker gem version to be overridden as an environment variable,
e.g. export BEAKER_VERSION=git://github.com/puppetlabs/beaker#<sha>
This also changes the default beaker version from ~> 2.2.0 to the master
branch for now.

(maint) Allow beaker version to be overridden

---

lib/hiera.rb
lib/hiera/backend.rb
lib/hiera/backend/json_backend.rb
lib/hiera/backend/yaml_backend.rb
spec/unit/backend_spec.rb

Prior to this commit it was not possible to provide deep merge options
in each call. The only way to use such options was to configure them
globally in the Hiera config. This commit changes this by allowing
the 'resolution_type' parameter to be a Hash and also ensure that is
propagated to the Backend::merge_answer() method.
When the 'resolution_type' is a hash, the merge_answer method will
completely disregard the Hiera deep merge config and instead pick the
merge behavior (keyed by :behavior) from the hash and consider the
deep merge options to the remaining top level entries of the hash.

(HI-348) Enable deep-merge options to be passed in lookup

---

Rakefile

When building packaging on jenkins, we don't have the rake library
available. Because of this, we try to load it in our Rakefile, it fails,
and then it bombs out and doesn't load anything else (aka the rake tasks
we use for packaging).
Since we also need to load rubygems and rspec/core/rake_task when
running `rake spec`. We need to be able to run spec tests in a repo
where the packaging repo hasn't been cloned and packaging.rake isn't
available. So we need to load these two different sets of libraries
separately.

(maint) Load packaging and spec tasks separately

---

acceptance/config/nodes/osx-1010-x86_64.yaml
acceptance/config/nodes/osx-109-x86_64.yaml
acceptance/config/nodes/ubuntu-1504-i386.yaml
acceptance/config/nodes/ubuntu-1504-x86_64.yaml

These are testing configs for the platforms that will be added to puppet-agent 1.2.0
They are the same files from puppetlabs/puppet#3972 and puppetlabs/puppet#3971 and puppetlabs/facter#962

(maint) [skip ci] Add puppet-agent 1.2.0 platforms

---

ext/hiera.yaml
lib/hiera/util.rb
spec/unit/backend_spec.rb
spec/unit/util_spec.rb

Prior to this commit, users had to configure hiera.yaml
before being able to use hiera. This commit defines a datadir
and a basic hierarchy to make it easier for users to get up
and running.
please see PE-894

(HI-374) configure hiera to work out of the box

---

ext/build_defaults.yaml

With the switch over to delivering software via the puppet agent
packages, we no longer need to maintain this list of build targets for
use by the packaging repo automation. We do want to keep some of this
around and available in the off chance that a community member has the
desire to build their own packages using the packaging repo automation.

(HI-369) Remove mock and cow build targets

---

lib/hiera/config.rb
lib/hiera/version.rb
spec/unit/backend_spec.rb
spec/unit/config_spec.rb

Before this the defaults expressed in the ext/hiera.yaml and the
internal code were different.
This makes them have the same content.

(HI-397) Add missing nodes/ entry to in code config defaults

---

acceptance/Gemfile
acceptance/setup/aio/pre-suite/010_Install.rb

Installs puppet-agent dmg on osx during aio acceptance, which depends on
beaker 2.16 or later.

(maint) Install dmg during osx acceptance

---

acceptance/config/nodes/centos-4-i386.yaml
acceptance/config/nodes/centos-4-x86_64.yaml
acceptance/config/nodes/centos-7-x86_64.yaml
acceptance/config/nodes/oracle-5-i386.yaml
acceptance/config/nodes/oracle-5-x86_64.yaml
acceptance/config/nodes/oracle-6-i386.yaml
acceptance/config/nodes/oracle-6-x86_64.yaml
acceptance/config/nodes/oracle-7-x86_64.yaml
acceptance/config/nodes/redhat-4-i386.yaml
acceptance/config/nodes/redhat-4-x86_64.yaml
acceptance/config/nodes/scientific-5-i386.yaml
acceptance/config/nodes/scientific-5-x86_64.yaml
acceptance/config/nodes/scientific-6-i386.yaml
acceptance/config/nodes/scientific-6-x86_64.yaml
acceptance/config/nodes/scientific-7-x86_64.yaml

For context, check #272. That was closed in favor of merging #277 & adding in this work, so that we have those platforms but in agent-only host files.
===begin original commit msg===
Prior to this there were no acceptance test host config files for PE
only platforms. The distinction between PE and FOSS is largely going
away (save for where the failures are reported).
This commit adds the necessary host configs to test Hiera against all
the platforms we will distribute puppet-agent on in the Shallow Gravy
timeframe.
[skip ci]

(MAINT) add PE platform configs

---

acceptance/Rakefile
acceptance/setup/peaio/pre-suite/010_Install.rb

before, :peaio was set to build from the pe_promoted repo.
this was a misunderstanding of the context of the pipeline
that this task is used in. this commit fixes that so that
it gets puppet-agent from the builds server.
[skip ci]

(PUP-4757) updated :peaio build location

---

Rakefile

Previously the check for the trailing paren was only made
for HI-<digits> (but not for maint or doc or packaging). This fixes
that regex.

(maint) Fix commits checker regex

---

acceptance/config/git/options.rb

Facter#master and stable require compiling to run, so for now pin
acceptance from git to use Facter#2.x.

(maint) Fix running acceptance from git

---

acceptance/config/nodes/solaris-10-sparc.yaml
acceptance/config/nodes/solaris-10-x86_64.yaml
acceptance/config/nodes/solaris-11-sparc.yaml
acceptance/config/nodes/solaris-11-x86_64.yaml

This commit adds node definitions for solaris sparc 10 and 11
agents using the SPARC architecture.

(HI-428) Add Solaris 10/11 SPARC node defs

---

acceptance/config/aio/options.rb
acceptance/config/git/options.rb
acceptance/config/packages/options.rb
acceptance/setup/common/pre-suite/000-delete-puppet-when-sparc.rb

This commit adds a beaker pre-suite to ensure that puppet packages
and components are removed when the platform is on sparc and the
hypervisor is none.
This ensures that the sparc testing platform does not have any
remaining puppet bits when it is not being managed by a provisioning
hypervisor.

(maint) Add acceptance pre-suite to rm puppet on sparc

---

lib/hiera/filecache.rb

Previously if a type error occurred during the file_read, the error
message would always say that the data retrieved is a string, and not
the expected type. This is because data comes from File.read, which
returns a string. Having the class of the data from the @cache object
allows the error message to be more helpful and return the class of the
parsed data instead of just 'String'.

(maint) Improve error message in read_file for filecache

---

acceptance/config/nodes/osx-1010-x86_64.yaml
acceptance/config/nodes/osx-109-x86_64.yaml
acceptance/config/nodes/ubuntu-1504-i386.yaml
acceptance/config/nodes/ubuntu-1504-x86_64.yaml

This commit removes master nodes from the node definitions
used for acceptance testing. Master nodes are not required
for hiera testing.

(HI-473) Remove master from acceptance node defs

---

lib/hiera/backend.rb

Previously, Hiera performed qualified key lookup by asking the backend for the
top-level key and descending into the data.  As an optimization, provide the
fully qualified key to the backend so that it can minimize processing required
to return a large data structure when only a small portion of it is used.  This
can speed up lookups for backends where processing data is expensive (like
eyaml).

(HI-471) Allow backends to perform qualified key lookup

---

acceptance/config/nodes/osx-1010-x86_64.yaml
acceptance/config/nodes/osx-1011-x86_64.yaml
acceptance/config/nodes/osx-109-x86_64.yaml
acceptance/lib/puppet/acceptance/install_utils.rb

Previously, beaker tried to install puppet-agent on OSX 10.11 twice
because the 'el' regex matched the elcapitan platform. When the 'el'
regex was made to be more specific, beaker added PermitUserEnvironment
to the pre 10.11 location, because beaker expects platform to contain
version numbers, not codenames.
This commit changes all OSX host configs to version numbers as
codenames, and makes the 'el' regex more specific, as 'el' could occur
in a future OS name.

(HI-443) Update platform field to use version numbers

---

lib/hiera/backend.rb
spec/unit/backend_spec.rb

We just created a project that uses hiera and active record. Active support is included automatically and also provides deep_merge. This deep merge does not allow additional options and is in that way not compatible. The deep_merge gem has a compatiblity mode for this, see https://github.com/danielsdeleo/deep_merge#using-deep_merge-in-rails
This commit adds the possibility to use the compatibility mode.

Added compatibility mode option for deep and deeper merge behavior

---

lib/hiera/backend.rb
lib/hiera/config.rb
spec/unit/backend_spec.rb

With this commit you can use hiera and active support in the same project.
See discussion in previous pull request https://github.com/puppetlabs/hiera/pull/324

(HI-483) Use compaitibility mode from deep_merge as default

---

lib/hiera/backend.rb
lib/hiera/interpolate.rb
spec/unit/backend_spec.rb
spec/unit/fixtures/interpolate/config/hiera_iplm_hiera.yaml
spec/unit/fixtures/interpolate/config/hiera_iplm_other.yaml
spec/unit/interpolate_spec.rb

Using interpolation methods in the hiera configuration configuration
file should be avoided. The 'hiera' method in particular will lead
to problems since it's very likely that it will cause an endless
recursion when a new attempt is made to read the configuration file.
This commit ensures that a deprecation warning is issued when the
interpolation method syntax is used in a hiera configuration file. An
error will be raised in case the 'hiera' interpolation method is used.

(HI-220) Deprecate use of interpolation methods in Hiera config

---

acceptance/Gemfile
acceptance/Rakefile

This commit adds a dependency on beaker-hostgenerator in the
acceptance Gemfile, which may be overridden using the
`BEAKER_HOSTGENERATOR_VERSION` environment variable.
The acceptance Rakefile will continue to use the `CONFIG` environment
variable, which must point to an existing host config file.
If `TEST_TARGET` is specified, it will override `CONFIG`, and the Rakefile
will use beaker-hostgenerator to dynamically generate a host config. The
host config is generated in the `acceptance/tmp` directory, as
opposed to `/tmp` so that it doesn't conflict with concurrent acceptance
tests running on the same CI coordinator. It also appends SecureRandom
to the hostfile, because it seems like a good idea. The resulting host
config is copied to the `log/latest/config.yml`.
For example, to run …

(HI-486) Allow host configs to be generated at runtime

---

acceptance/Gemfile
acceptance/Rakefile

The puppet-agent components need the osinfo version 1 of b-hg,
so that centos4 is correctly specified as a platform name, so
that puppet-agent can be installed on centos4.
This commit moves to b-hg 0.3.1, the first version implementing
that, and specifies the osinfo version when invoking b-hg.

(HI-486) Bump to beaker-hostgenerator 0.3.1

---

install.rb

With the switch over to building puppet-agent for windows with Vanagon,
we need to effectively install hiera with install.rb. This script
installs hiera.bat, which is a wrapper that lets windows handle ruby
scripts. This commit updates hiera.bat to use our environment.bat file if
we install it, and to be more in line with the hiera.bat file installed
with the puppet-agent package as built by puppet_for_the_win
This takes advantage of `environment.bat` in puppet-agent installed with https://github.com/puppetlabs/puppet-agent/pull/512

(HI-943) Update hiera.bat to current standard

---

lib/hiera/interpolate.rb
spec/unit/fixtures/interpolate/config/hiera.yaml
spec/unit/fixtures/interpolate/data/empty_interpolation.yaml
spec/unit/interpolate_spec.rb

Before this, we started doing something wrong in the hiera 3.x series as
interpolation of empty strings 
See commit for details.

(HI-494) Bring back support for empty interpolation

---

README.md

Calling `.values` on the loaded facts scope breaks the example. Not sure
why that's there.

(maint) Fix erroneous use of .value in README

---

lib/hiera/config.rb
spec/unit/backend_spec.rb

Before this, if a backend could not be loaded, this was only logged as a
warning and hiera merrily continued by serving data from remaining (if
any) backends.
This can lead to catastrophic results as lookups may be resolved with
large portions of the data missing. This in turn can cause catalogs to
contain a radically different configuration causing a wide range of
unpleasant surprises.

(HI-499) Fail if backend cannot be loaded

---

lib/hiera/backend.rb
spec/unit/fixtures/interpolate/data/dotted_keys.yaml
spec/unit/interpolate_spec.rb

Before this commit, a subkey of a dotted key could be matched by a
string that contained a matching text. Hiera would require that the
value
responded to :[] and that it was not an Array (arrays should use numeric
index). A string fulfills that requirement.
This commit adds the constraint that the value cannot be a String when
subjected to a lookup.

(HI-508) Prevent that subkeys can do lookups in string values

---

lib/hiera/backend.rb
lib/hiera/interpolate.rb
spec/unit/backend_spec.rb
spec/unit/interpolate_spec.rb

This commit removes mentioning of 'segmented keys' in favor of wording
using 'dotted keys' and 'access' and adds the offending key to related
error messages.

(HI-502) Improve error reporting when using dotted keys.

---

bin/hiera
lib/hiera.rb
lib/hiera/util.rb
spec/unit/hiera_spec.rb
spec/unit/util_spec.rb

This commit ensures that when Hiera is initialized, it will first check
if a config file is specified using a CLI option. If it is, then that
config will be used (and an error is raised if it doesn't exist). When
no CLI option is used, Hiera will first look `hiera.yaml` in the
codedir and if no such file exists, it will default to `hiera.yaml`
in confdir.

(HI-510) Look for hiera.yaml in codedir first, then confdir

---

install.rb

puppet-agent carries the batch files for all executables with the new move to
vanagon for windows projects, we will need an option to omit batch file
creation during installation of hiera so there are not more than one set of
batch files. So this commit adds a --no-batch-files option for cmake that omits
those files.

(HI-515) Add --no-batch-files option

---

.gemspec
Gemfile
ext/project_data.yaml

json_pure was added as a dependency to hiera to enable easier development
with ruby 1.8.7 (which doesn't include a json implementation). With hiera
now supporting only ruby 1.9.3+, the dependency is no longer needed.

(HI-528) Remove json_pure dependency

---

lib/hiera/backend.rb

As per discussion in Puppetlabs git ticket [HI-530](https://tickets.puppetlabs.com/browse/HI-530) 
report when we have skipped "bad definition in :hierarchy"

 report when we have skipped "bad definition in :hierarchy"

---

acceptance/Gemfile

Update the beaker gem version used in acceptance to beaker 3.1.0 to allow for
MacOS Sierra (10.12) testing.

(HI-538) Update beaker version to 3.1.0

---

acceptance/Gemfile

This reverts commit bf52672cee19a9d712394c0acdedb05f5970e93f.
All jenkins pipelines for hiera need to be updated to use ruby >= 2.2.5 before
this will work

Revert "(HI-538) Update beaker version to 3.1.0"

---

acceptance/Gemfile

Reverts puppetlabs/hiera#366
Jenkins pipelines now have ruby 2.3.1

Revert "Revert "(HI-538) Update beaker version to 3.1.0""

---

lib/hiera/version.rb

This updates Hiera's version to 3.2.2 in preparation for the
puppet-agent 1.8.0 release. We had originally updated the version from
3.2.1 to 3.3.0, but the small amount of changes made a Y release
unnecessary.

(packaging) Bump version to 3.2.2

---

acceptance/Gemfile
lib/hiera/backend.rb
lib/hiera/version.rb

This merge is in anticipation of the puppet-agent 1.8.0 release, and includes the 3.2.2 tag, along with everything slated for that release.

Merge master to stable

---

lib/hiera/version.rb

This bumps the Hiera version to 3.2.3 following the release of 3.2.2 as
part of puppet-agent 1.8.0.

(PA-652) Bump Hiera version to 3.2.3

---

lib/hiera/config.rb
spec/unit/config_spec.rb
spec/unit/fixtures/badconfig/config/hiera.yaml
spec/unit/fixtures/badconfig/data/common.yaml

This commit adds a check for a `version` field in the hiera.yaml config
file. If the version is present and indicates a number greater than 3, then
the load fails with an error.

(HI-544) Fail with meaningful message on hiera configs with version > 3

---

lib/hiera/filecache.rb
spec/unit/filecache_spec.rb

Unless supplied an encoding, File.read will read in files with whatever Ruby's
default external encoding is, which on Windows may be an encoding such as
IBM437. Prior to this commit, hiera's FileCache#read_file method would call
File.read without an encoding, which could be problematic when reading files
containing unicode or other characters undefined on such a platform. This
commit updates the #read_file method to explicitly read files in with
BOM|UTF-8.

(HI-519) Read files in with unicode

---

lib/hiera/version.rb

Bump Hiera to v3.3.0, which will be included in puppet-agent 1.9.0.

(packaging) Bump Hiera version to 3.3.0

---

Gemfile
appveyor.yml
ext/project_data.yaml
install.rb
lib/hiera.rb
lib/hiera/util.rb
lib/hiera/util/win32.rb
spec/spec_helper.rb

* Adds AppVeyor support for pull requests
* Removes win32console gem
* Removes win32-dir gem / replaces COMMON_APPDATA resolution with call to Windows API `SHGetFolderPath`
* Removes `project_data.yaml` gem definitions - resulting in no more platform specific gems for Windows

(HI-346) Remove unnecessary Windows gems

---

CONTRIBUTING.md

Supersedes https://github.com/puppetlabs/hiera/pull/394, with commit message amended to reference HI ticket

(HI-571) Tech-debt: links.puppetlabs.com -> links.puppet.com

---

lib/hiera/version.rb

This commit updates the version of Hiera to 3.4.0 in preparation for the
Puppet Agent 5.0.0 release.

(packaging) Bump version to 3.4.0

---

.gemspec

Rubygems has some undesirable behavior when doing dependency solving
with versions that are looked up from within a library. This can be seen
when using the rubygems in the puppet-agent package to install r10k, and
then installing a second version of a gem that r10k depends on, such as
minitar.
When more than one version of a dependent gem is installed, rubygems
loads all of the gemspecs and tries to decide which gems to activate.
When loading all of the gemspecs, rubygems encounters the require on
`hiera/version`, which brings us to the second half of our story.
Rubygems monkey patches `Kernel.require` to first search gems for a path
before searching the load path. This means that to find
`hiera/version`, rubygems first looks through all of the gems it knows
about, which means loading …

(HI-579) Begin hard-coding hiera version in the gemspec

---

.travis.yml
lib/hiera/config.rb

Now that hiera 5 configs exist this error message can be thrown from a
hiera 5 config in which case the error message is very confusing. This
commit includes the actual hiera config version in the error message
instead of assuming it will be 4.

(maint) Reference actual config version in error message

---

bin/hiera

We are deprecating mcollective for Platform 6, so this bit of code
is no longer needed.

(HI-601) Remove feature to read facts from an mcollective server

---

ext/build_defaults.yaml

More of a formality to remove references of our soon-to-expire GPG
key.
Under normal circumstances this setting from ext/build_defaults.yaml
is ignored in favor of https://github.com/puppetlabs/build-data/blob/5c6466dd0427773df6064b33354dedb9161d5845/builder_data.yaml#L3

(RE-13431) Remove reference to 'gpg_key'

---

acceptance/Gemfile

This is the Gemfile used during beaker testing, not the main Gemfile.

(maint) upgrade rake due to CVE-2020-8130

---

lib/hiera/version.rb

We need to release Hiera 3.9.0 for the upcoming Puppet 6.27.0
release. In 404ea2e, our automation accidentally skipped 3.9.0
and went straight to 3.10.0.
After this is merged, I plan on running a package validation
pipeline that will add the corresponding 3.9.0 tag.

(packaging) Sets version to 3.9.0 for release

---

.gemspec

Ruby 2.5 is the oldest version that's tested in CI. the gemspec should
reflect that.

Set minimal ruby version to 2.5 in gemspec

---

.github/workflows/rspec_tests.yaml
Gemfile

In preparation for Puppet 8, which will likely use Ruby 3.2, this commit adds Ruby 3.2.0-preview2 to the Linux rspec tests matrix and the latest available Ruby version for Windows (3.1).

(HI-635) Adds Ruby 3.2 to rspec tests

---

.github/workflows/checks.yaml
.github/workflows/rspec_tests.yaml

GitHub is deprecating Ubuntu 18.04 runners on April 1, 2023. This commit switches all Ubuntu 18.04 used in GitHub Actions to ubuntu-latest (currently Ubuntu 20.04).

(HI-636) Updates Ubuntu GitHub Actions runners

---

.github/workflows/checks.yaml
.github/workflows/rspec_tests.yaml
install.rb

FileUtils in ruby 3.x doesn't accept passing args as a hash.

(maint) Use keyword arguments
